import type { NormalizedJob } from "./types";

/**
 * MODE DÉMO — DONNÉES FICTIVES.
 *
 * These listings are entirely fictional, created for local development and
 * demonstration only. They are never presented to users as real job offers:
 * every job sourced from this adapter is tagged with `JobSource.kind =
 * "DEMO"`, and the UI must render a visible "Offre de démonstration" badge
 * wherever such a job appears (see JobCard / job detail page). Company
 * names, addresses and contact details below are invented.
 *
 * Coordinates are approximate city-center points for a handful of French
 * cities, used so the location-matching dimension has real numbers to work
 * with in demo mode.
 */

const CITY_COORDS: Record<string, { lat: number; lng: number; postcode: string; region: string }> = {
  Paris: { lat: 48.8566, lng: 2.3522, postcode: "75011", region: "Île-de-France" },
  Lyon: { lat: 45.764, lng: 4.8357, postcode: "69003", region: "Auvergne-Rhône-Alpes" },
  Marseille: { lat: 43.2965, lng: 5.3698, postcode: "13006", region: "Provence-Alpes-Côte d'Azur" },
  Bordeaux: { lat: 44.8378, lng: -0.5792, postcode: "33000", region: "Nouvelle-Aquitaine" },
  Lille: { lat: 50.6292, lng: 3.0573, postcode: "59000", region: "Hauts-de-France" },
  Toulouse: { lat: 43.6047, lng: 1.4442, postcode: "31000", region: "Occitanie" },
  Nantes: { lat: 47.2184, lng: -1.5536, postcode: "44000", region: "Pays de la Loire" },
  Strasbourg: { lat: 48.5734, lng: 7.7521, postcode: "67000", region: "Grand Est" },
};

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

interface DemoJobTemplate extends Omit<NormalizedJob, "publishedAt" | "url" | "externalId" | "latitude" | "longitude" | "postcode" | "region"> {
  city: string;
  publishedDaysAgo: number;
}

const templates: DemoJobTemplate[] = [
  {
    title: "Vendeur / Vendeuse en boutique de mode — job étudiant",
    companyName: "Atelier Fil & Style",
    description:
      "Nous recherchons un(e) vendeur/vendeuse polyvalent(e) pour renforcer notre équipe le soir et le samedi. Vous accueillez la clientèle, conseillez sur les collections, tenez la caisse et participez à la mise en rayon.",
    missions: "Accueil et conseil client, encaissement, mise en rayon, gestion des cabines d'essayage.",
    city: "Paris",
    contractType: "CDD",
    experienceLevel: "STUDENT",
    salaryMin: 11, salaryMax: 12, salaryPeriod: "HOUR",
    hoursPerWeek: 15,
    schedule: "Mardi et jeudi 17h-20h, samedi 10h-19h",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Vente", "Service client", "Caisse"],
    languages: ["Français"],
    publishedDaysAgo: 1,
  },
  {
    title: "Serveur / Serveuse — soirs et week-ends",
    companyName: "Le Bistrot des Halles",
    description:
      "Restaurant convivial cherche serveur/serveuse pour le service du soir et les week-ends. Une première expérience en restauration est un plus mais n'est pas indispensable, la motivation prime.",
    missions: "Prise de commandes, service en salle, dressage des tables, relation client.",
    city: "Lyon",
    contractType: "MISSION",
    experienceLevel: "ENTRY",
    salaryMin: 11, salaryMax: 11.5, salaryPeriod: "HOUR",
    hoursPerWeek: 12,
    schedule: "Vendredi et samedi soir, dimanche midi",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Service client", "Gestion du stress"],
    languages: ["Français"],
    publishedDaysAgo: 2,
  },
  {
    title: "Développeur Web Junior React/Node",
    companyName: "Nova Digital",
    description:
      "Startup en forte croissance recherche un développeur web junior pour rejoindre son équipe produit. Vous travaillerez sur notre application React/Node.js en collaboration avec deux développeurs seniors.",
    missions: "Développement de fonctionnalités front-end React, API Node.js, tests, revue de code.",
    city: "Paris",
    contractType: "CDI",
    experienceLevel: "JUNIOR",
    salaryMin: 2400, salaryMax: 2800, salaryPeriod: "MONTH",
    hoursPerWeek: 37,
    schedule: "Lundi-vendredi, horaires flexibles",
    remoteType: "HYBRID",
    requiredSkills: ["JavaScript", "TypeScript", "React", "Node.js", "Git"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 3,
  },
  {
    title: "Assistant Marketing Digital — Stage",
    companyName: "Kaïros Agency",
    description:
      "Agence marketing digital cherche un(e) stagiaire assistant marketing pour accompagner l'équipe sur la gestion de campagnes SEA/SEO et l'animation des réseaux sociaux de nos clients.",
    missions: "Création de contenus, suivi de campagnes publicitaires, reporting, veille concurrentielle.",
    city: "Paris",
    contractType: "STAGE",
    experienceLevel: "STUDENT",
    salaryMin: 700, salaryMax: 900, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Lundi-vendredi",
    remoteType: "HYBRID",
    requiredSkills: ["Marketing digital", "PowerPoint", "Excel", "Créativité"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 5,
  },
  {
    title: "Chargé(e) de clientèle — service client",
    companyName: "Assurgo",
    description:
      "Rejoignez notre centre de relation client pour accompagner nos assurés par téléphone et email. Formation assurée à l'arrivée.",
    missions: "Réponse aux demandes clients, traitement des dossiers, satisfaction client.",
    city: "Bordeaux",
    contractType: "CDD",
    experienceLevel: "ENTRY",
    salaryMin: 1800, salaryMax: 1900, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Lundi-vendredi 9h-17h",
    remoteType: "HYBRID",
    requiredSkills: ["Service client", "Communication", "Excel"],
    languages: ["Français"],
    publishedDaysAgo: 4,
  },
  {
    title: "Livreur / Livreuse à vélo — soirs",
    companyName: "QuickMeal Express",
    description:
      "Livraison de repas à vélo ou scooter sur des créneaux flexibles en soirée. Idéal en complément d'études.",
    missions: "Récupération des commandes en restaurant, livraison chez les clients.",
    city: "Toulouse",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 12, salaryMax: 14, salaryPeriod: "HOUR",
    hoursPerWeek: 10,
    schedule: "Créneaux libres, 18h-22h de préférence",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Permis B"],
    languages: ["Français"],
    publishedDaysAgo: 1,
  },
  {
    title: "Animateur / Animatrice périscolaire",
    companyName: "Ville de Nantes — Enfance & Loisirs",
    description:
      "La ville de Nantes recrute des animateurs pour l'accueil périscolaire du matin et du soir ainsi que le mercredi.",
    missions: "Encadrement d'enfants de 6 à 11 ans, animation d'ateliers, sécurité des enfants.",
    city: "Nantes",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 11.5, salaryMax: 11.5, salaryPeriod: "HOUR",
    hoursPerWeek: 8,
    schedule: "Lundi, mardi, jeudi, vendredi 7h30-8h30 et 16h30-18h30",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Travail d'équipe", "Organisation"],
    languages: ["Français"],
    publishedDaysAgo: 6,
  },
  {
    title: "Développeur Full-Stack — Alternance",
    companyName: "Lumo Software",
    description:
      "Éditeur de logiciels SaaS recherche un(e) alternant(e) développeur full-stack pour préparer un diplôme d'ingénieur ou un master informatique.",
    missions: "Développement de nouvelles fonctionnalités, participation aux choix techniques, tests automatisés.",
    city: "Lille",
    contractType: "ALTERNANCE",
    experienceLevel: "STUDENT",
    salaryMin: 900, salaryMax: 1400, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Lundi-vendredi",
    remoteType: "HYBRID",
    requiredSkills: ["JavaScript", "TypeScript", "React", "SQL", "Git"],
    languages: ["Français"],
    publishedDaysAgo: 8,
  },
  {
    title: "Hôte / Hôtesse de caisse",
    companyName: "Marché Frais",
    description:
      "Supermarché de quartier recherche un(e) hôte(sse) de caisse pour compléter son équipe, disponibilités le week-end appréciées.",
    missions: "Encaissement, contrôle des produits, relation client, tenue du poste de caisse.",
    city: "Marseille",
    contractType: "CDD",
    experienceLevel: "ENTRY",
    salaryMin: 11.7, salaryMax: 11.7, salaryPeriod: "HOUR",
    hoursPerWeek: 20,
    schedule: "Samedi et dimanche + 2 soirs en semaine",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Caisse", "Service client", "Ponctualité"],
    languages: ["Français"],
    publishedDaysAgo: 2,
  },
  {
    title: "Chef de projet marketing",
    companyName: "Bloomly",
    description:
      "Nous recherchons un chef de projet marketing expérimenté pour piloter nos campagnes multicanal et encadrer une petite équipe.",
    missions: "Pilotage de campagnes, gestion budgétaire, coordination avec les agences, reporting à la direction.",
    city: "Paris",
    contractType: "CDI",
    experienceLevel: "SENIOR",
    salaryMin: 3800, salaryMax: 4500, salaryPeriod: "MONTH",
    hoursPerWeek: 39,
    schedule: "Lundi-vendredi",
    remoteType: "HYBRID",
    requiredSkills: ["Marketing digital", "Gestion de projet", "Leadership", "PowerPoint"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 10,
  },
  {
    title: "Data Analyst",
    companyName: "Insighta",
    description:
      "Cabinet de conseil en données recherche un data analyst pour accompagner nos clients dans l'exploitation de leurs données métier.",
    missions: "Analyse de données, création de tableaux de bord, présentation des résultats aux clients.",
    city: "Paris",
    contractType: "CDI",
    experienceLevel: "JUNIOR",
    salaryMin: 2700, salaryMax: 3200, salaryPeriod: "MONTH",
    hoursPerWeek: 37,
    schedule: "Lundi-vendredi, télétravail possible",
    remoteType: "REMOTE_ONLY",
    requiredSkills: ["Python", "SQL", "Data Analysis", "Excel"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 3,
  },
  {
    title: "Assistant(e) comptable — Alternance",
    companyName: "Cabinet Vasseur & Associés",
    description:
      "Cabinet d'expertise comptable recherche un(e) alternant(e) pour préparer un BTS ou DCG comptabilité.",
    missions: "Saisie comptable, rapprochements bancaires, préparation de déclarations de TVA.",
    city: "Lyon",
    contractType: "ALTERNANCE",
    experienceLevel: "STUDENT",
    salaryMin: 800, salaryMax: 1200, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Lundi-vendredi",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Comptabilité", "Excel", "Rigueur"],
    languages: ["Français"],
    publishedDaysAgo: 7,
  },
  {
    title: "Community Manager — Freelance",
    companyName: "Studio Griotte",
    description:
      "Studio créatif cherche un community manager freelance pour gérer les réseaux sociaux de plusieurs clients (mode, food, lifestyle).",
    missions: "Création de contenus, planning éditorial, community management, reporting mensuel.",
    city: "Nantes",
    contractType: "FREELANCE",
    experienceLevel: "JUNIOR",
    salaryMin: 20, salaryMax: 30, salaryPeriod: "HOUR",
    hoursPerWeek: 15,
    schedule: "Flexible",
    remoteType: "REMOTE_ONLY",
    requiredSkills: ["Marketing digital", "Créativité", "Photoshop"],
    languages: ["Français"],
    publishedDaysAgo: 4,
  },
  {
    title: "Serveur / Serveuse — job étudiant week-end",
    companyName: "Café de la Place",
    description:
      "Café-brasserie cherche un(e) serveur/serveuse pour le service du samedi et dimanche uniquement, idéal pour un job étudiant.",
    missions: "Service en salle, prise de commandes, encaissement.",
    city: "Paris",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 11, salaryMax: 11.5, salaryPeriod: "HOUR",
    hoursPerWeek: 14,
    schedule: "Samedi et dimanche 9h-16h",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Service client", "Ponctualité"],
    languages: ["Français"],
    publishedDaysAgo: 1,
  },
  {
    title: "Vendeur / Vendeuse — saison d'été",
    companyName: "Surf & Co",
    description:
      "Boutique de sports de glisse recrute pour la saison estivale. Contrat saisonnier de juin à septembre.",
    missions: "Conseil client, vente, réassort, animation de la boutique.",
    city: "Bordeaux",
    contractType: "SAISONNIER",
    experienceLevel: "ENTRY",
    salaryMin: 1750, salaryMax: 1800, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "6 jours sur 7 en haute saison",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Vente", "Service client"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 12,
  },
  {
    title: "Préparateur / Préparatrice de commandes — nuit",
    companyName: "LogiFret",
    description:
      "Entrepôt logistique recherche des préparateurs de commandes pour l'équipe de nuit, formation CACES fournie si besoin.",
    missions: "Préparation de commandes, utilisation d'un scanner, respect des cadences.",
    city: "Toulouse",
    contractType: "INTERIM",
    experienceLevel: "ENTRY",
    salaryMin: 12, salaryMax: 12.5, salaryPeriod: "HOUR",
    hoursPerWeek: 30,
    schedule: "22h-5h, du lundi au vendredi",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Logistique", "Rigueur"],
    languages: ["Français"],
    publishedDaysAgo: 5,
  },
  {
    title: "Garde d'enfants à domicile",
    companyName: "Kidiligo",
    description:
      "Famille recherche une personne pour la garde de deux enfants (6 et 9 ans) après l'école, du lundi au jeudi.",
    missions: "Sortie d'école, aide aux devoirs, activités, goûter.",
    city: "Lyon",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 12, salaryMax: 13, salaryPeriod: "HOUR",
    hoursPerWeek: 8,
    schedule: "Lundi-jeudi 16h30-18h30",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Sens du relationnel", "Ponctualité"],
    languages: ["Français"],
    publishedDaysAgo: 2,
  },
  {
    title: "Professeur particulier — soutien scolaire mathématiques",
    companyName: "Réussite+",
    description:
      "Organisme de soutien scolaire recherche des étudiants en école d'ingénieur ou de commerce pour donner des cours particuliers de mathématiques niveau collège/lycée.",
    missions: "Cours particuliers à domicile ou en visio, suivi pédagogique.",
    city: "Strasbourg",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 15, salaryMax: 20, salaryPeriod: "HOUR",
    hoursPerWeek: 5,
    schedule: "Selon disponibilités, en semaine en soirée",
    remoteType: "HYBRID",
    requiredSkills: ["Communication", "Rigueur"],
    languages: ["Français"],
    publishedDaysAgo: 3,
  },
  {
    title: "Réceptionniste — hôtel 3 étoiles",
    companyName: "Hôtel Belrive",
    description:
      "Hôtel familial recherche un(e) réceptionniste pour les week-ends et remplacements de vacances.",
    missions: "Accueil des clients, check-in/check-out, réservations, standard téléphonique.",
    city: "Marseille",
    contractType: "CDD",
    experienceLevel: "ENTRY",
    salaryMin: 1850, salaryMax: 1950, salaryPeriod: "MONTH",
    hoursPerWeek: 24,
    schedule: "Vendredi, samedi, dimanche",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Service client", "Anglais", "Organisation"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 6,
  },
  {
    title: "Ingénieur logiciel confirmé — Backend",
    companyName: "Nova Digital",
    description:
      "Nous renforçons notre équipe backend avec un ingénieur logiciel confirmé maîtrisant les architectures distribuées et Node.js.",
    missions: "Conception d'API, optimisation des performances, mentorat des développeurs juniors.",
    city: "Paris",
    contractType: "CDI",
    experienceLevel: "SENIOR",
    salaryMin: 4200, salaryMax: 5200, salaryPeriod: "MONTH",
    hoursPerWeek: 37,
    schedule: "Lundi-vendredi, télétravail 3j/semaine",
    remoteType: "HYBRID",
    requiredSkills: ["Node.js", "TypeScript", "Docker", "SQL", "Leadership"],
    languages: ["Français", "Anglais"],
    publishedDaysAgo: 9,
  },
  {
    title: "Assistant(e) administratif(ve) — temps partiel",
    companyName: "Cabinet Juris Conseil",
    description:
      "Cabinet d'avocats recherche un(e) assistant(e) administratif(ve) à temps partiel pour la gestion du courrier, des agendas et de l'accueil téléphonique.",
    missions: "Accueil téléphonique, gestion des agendas, classement de dossiers, frappe de courriers.",
    city: "Lille",
    contractType: "CDD",
    experienceLevel: "ENTRY",
    salaryMin: 1500, salaryMax: 1600, salaryPeriod: "MONTH",
    hoursPerWeek: 20,
    schedule: "Lundi, mercredi, vendredi 9h-17h",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Word", "Excel", "Organisation", "Communication"],
    languages: ["Français"],
    publishedDaysAgo: 4,
  },
  {
    title: "Barista — coffee shop",
    companyName: "Grain de Café",
    description:
      "Coffee shop indépendant recherche un(e) barista passionné(e) pour rejoindre une petite équipe conviviale.",
    missions: "Préparation des boissons, service au comptoir, encaissement, entretien du poste.",
    city: "Bordeaux",
    contractType: "CDI",
    experienceLevel: "ENTRY",
    salaryMin: 1750, salaryMax: 1800, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Du mardi au samedi, 7h-15h ou 12h-20h",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Service client", "Ponctualité", "Autonomie"],
    languages: ["Français"],
    publishedDaysAgo: 5,
  },
  {
    title: "Stagiaire Ressources Humaines",
    companyName: "GroupeAlliance",
    description:
      "Notre direction des ressources humaines recherche un(e) stagiaire pour accompagner le recrutement et l'intégration des nouveaux collaborateurs.",
    missions: "Tri de CV, planification d'entretiens, suivi de l'intégration, mise à jour des dossiers RH.",
    city: "Toulouse",
    contractType: "STAGE",
    experienceLevel: "STUDENT",
    salaryMin: 700, salaryMax: 800, salaryPeriod: "MONTH",
    hoursPerWeek: 35,
    schedule: "Lundi-vendredi",
    remoteType: "HYBRID",
    requiredSkills: ["Communication", "Organisation", "Word"],
    languages: ["Français"],
    publishedDaysAgo: 7,
  },
  {
    title: "Vendeur / Vendeuse rayon frais — week-end",
    companyName: "Marché Frais",
    description:
      "Notre supermarché recherche un renfort le week-end pour le rayon fruits et légumes.",
    missions: "Mise en rayon, rotation des produits, conseil client, propreté du rayon.",
    city: "Marseille",
    contractType: "MISSION",
    experienceLevel: "STUDENT",
    salaryMin: 11.7, salaryMax: 11.7, salaryPeriod: "HOUR",
    hoursPerWeek: 12,
    schedule: "Samedi et dimanche 8h-14h",
    remoteType: "ONSITE_ONLY",
    requiredSkills: ["Organisation", "Ponctualité"],
    languages: ["Français"],
    publishedDaysAgo: 1,
  },
];

export function buildDemoJobs(): NormalizedJob[] {
  return templates.map((t, i) => {
    const coords = CITY_COORDS[t.city];
    const { city, publishedDaysAgo, ...rest } = t;
    return {
      ...rest,
      city,
      postcode: coords.postcode,
      region: coords.region,
      country: "FR",
      latitude: coords.lat,
      longitude: coords.lng,
      externalId: `demo-${i + 1}`,
      url: `https://exemple-demo.invalid/offres/demo-${i + 1}`,
      publishedAt: daysAgo(publishedDaysAgo),
    };
  });
}
